/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

/// <reference path="../../../sst-env.d.ts" />

<<<<<<< HEAD
import "sst"
export {}
=======
import "sst";
export {};
>>>>>>> f9b8045 (Update semua)
